version: "3.6"
services:
  postgres:
    image: postgres:10
    # make sure that your db local storage will be located on one node. If you have several nodes
    # you could use this vvv to pin the container
    # deploy:
    #   placement:
    #     constraints: [node.hostname == node-name]
    volumes:
      # don't forget to locally create folders for persistent storage
      - /opt/postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: mentoring
      DB_USERNAME: mentoring
      DB_USERPASS: /run/secrets/db_userpass
    configs:
      - source: update-postgres-configs.sh
        target: /docker-entrypoint-initdb.d/update-postgres-configs.sh
        mode: 0555
      - source: init-mentoring-user-db.sh
        target: /docker-entrypoint-initdb.d/init-mentoring-user-db.sh
        mode: 0555
    secrets:
      - db_userpass
  postfix:
    image: boky/postfix:latest
    environment:
      # @see: https://hub.docker.com/r/boky/postfix/
      # set variables as you need
      ALLOWED_SENDER_DOMAINS: <you sender domain>
  mentoring:
    image: mentoring:latest
    # wait till postgres loads
    command: sh -c './script/wait-for postgres:5432 -- ./script/run'
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      HTTP_HOST: nastavnik24.ru
      DB_HOST: postgres
      DB_NAME: mentoring
      DB_USERNAME: mentoring
      DB_USERPASS: /run/secrets/db_userpass
      # setting up gmail as smtp is optional if you want to use internal postfix, it will be used
      # when you leave this variable commented out, otherwise gmail will be used
      # GMAIL_USER: <gmail address here>
      GMAIL_PASS: /run/secrets/gmail_password
      MAILER_SENDER: '"Программа Детский дом" <nastavnichestvo@inbox.ru>'
      ADMIN_EMAIL: <admin email here>
      ADMIN_PASSWORD: /run/secrets/admin_password
      # must be generated via `bin/rails secrets`
      SECRET_KEY_BASE: /run/secrets/secret_key_base
      LANG: en_US.UTF-8
    secrets:
      - db_userpass
      - gmail_password
      - admin_password
      - secret_key_base
configs:
  # these files must be in the <folder there this file located>/script folder before building an image
  migrate.sh:
    file: script/migrate
  run.sh:
    file: script/run
  init-mentoring-user-db.sh:
    file: script/init-mentoring-user-db.sh
  update-postgres-configs.sh:
    file: script/update-postgres-configs.sh
secrets:
  # these files must be in the <folder there this file located>/secrets folder before building an image
  db_userpass:
    file: secrets/db_userpass
  # this is optional
  gmail_password:
    file: secrets/gmail_password
  admin_password:
    file: secrets/admin_password
  secret_key_base:
    file: secrets/secret_key_base
